using DeepSeekBrowser.Models;
using DeepSeekBrowser.Services;
using DeepSeekBrowser.Services.ApiManagement;

namespace DeepSeek.Core.Tests;

public sealed class AgentDesktopConfigSyncTests : TestConfigIsolation
{
    [Fact]
    public void Apply_writes_deepseek_home_config_files()
    {
        var token = "test-token-" + Guid.NewGuid().ToString("N");
        var cfg = new AppConfig
        {
            AgentApprovalMode = "smart",
            DefaultAgentStrategy = AgentStrategies.Blueprint,
            WebUserToken = token
        };
        cfg.McpServers.Add(new McpServerConfig { Name = "fs", Enabled = true, Command = "npx", Arguments = ["-y", "test"] });
        ProviderAccountStore.Add("deepseek", "Test", new Dictionary<string, string> { ["token"] = token });

        AgentDesktopConfigSync.Apply(cfg);

        var toml = File.ReadAllText(AgentDesktopConfigSync.ConfigPath);
        Assert.Contains("Generated by DeepSeek Desktop", toml);
        Assert.Contains("approval_mode", toml);
        Assert.Contains("default_mode = \"plan\"", toml);
        Assert.Contains(token, toml);

        var json = File.ReadAllText(AgentDesktopConfigSync.McpPath);
        Assert.Contains("mcpServers", json);
    }
}
