using DeepSeekBrowser.Models;
using DeepSeekBrowser.Services;

namespace DeepSeek.Core.Tests;

public sealed class AgentDesktopConfigSyncTests
{
    [Fact]
    public void Apply_writes_deepseek_home_config_files()
    {
        var cfg = new AppConfig
        {
            AgentApprovalMode = "smart",
            DefaultAgentStrategy = AgentStrategies.Blueprint,
            WebUserToken = "test-token-" + Guid.NewGuid().ToString("N")
        };
        cfg.McpServers.Add(new McpServerConfig { Name = "fs", Enabled = true, Command = "npx", Arguments = ["-y", "test"] });

        AgentDesktopConfigSync.Apply(cfg);

        var toml = File.ReadAllText(AgentDesktopConfigSync.ConfigPath);
        Assert.Contains("Generated by DeepSeek Desktop", toml);
        Assert.Contains("approval_mode", toml);
        Assert.Contains("default_mode = \"plan\"", toml);
        Assert.Contains(cfg.WebUserToken, toml);

        var json = File.ReadAllText(AgentDesktopConfigSync.McpPath);
        Assert.Contains("mcpServers", json);
    }
}
