using System.IO;
using System.Text;
using System.Text.Json;
using DeepSeekBrowser.Models;
using DeepSeekBrowser.Services.Harness;
using DeepSeekBrowser.Services.Harness.Interop;

namespace DeepSeekBrowser.Services;

/// <summary>
/// 将桌面端 Agent / MCP 设置同步到 <c>~/.deepseek/</c>（供外部工具与技能目录兼容）。
/// </summary>
public static class AgentDesktopConfigSync
{
    private static readonly object WriteGate = new();

    public static string HomeDirectory =>
        Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".deepseek");

    public static string ConfigPath => Path.Combine(HomeDirectory, "config.toml");

    public static string McpPath => Path.Combine(HomeDirectory, "mcp.json");

    public static void Apply(AppConfig config)
    {
        lock (WriteGate)
        {
            Directory.CreateDirectory(HomeDirectory);
            Directory.CreateDirectory(Path.Combine(HomeDirectory, "skills"));
            EnsureDefaultPlaybooks();
            EnsureDefaultMemory();

            WriteConfigToml(config);
            WriteMcpJson(config);
            WriteBuiltinToolSchema();
        }
    }

    private static void WriteConfigToml(AppConfig config)
    {
        var snap = Chat2ApiProviderService.Build(config);
        var apiKey = snap.ApiKeyForClients;
        var llmBaseUrl = InternalChatChannel.ResolveTuiLlmBaseUrl(config);

        var defaultMode = HarnessStrategyResolver.IsBlueprintWorkflow(config.DefaultAgentStrategy)
            ? "plan"
            : "agent";

        var approval = MapApprovalMode(config.AgentApprovalMode);

        var sb = new StringBuilder();
        sb.AppendLine("# Generated by DeepSeek Desktop (native Harness)");
        sb.AppendLine("# LLM：进程内网页桥 + Chat2API；不经独立 TUI 子进程");
        sb.AppendLine();
        sb.AppendLine($"api_key = \"{EscapeToml(apiKey)}\"");
        if (!string.IsNullOrWhiteSpace(llmBaseUrl))
            sb.AppendLine($"base_url = \"{EscapeToml(llmBaseUrl)}\"");
        sb.AppendLine("default_text_model = \"deepseek-v4-pro\"");
        sb.AppendLine();
        sb.AppendLine("[ui]");
        sb.AppendLine($"default_mode = \"{defaultMode}\"");
        sb.AppendLine($"approval_mode = \"{approval}\"");
        sb.AppendLine("reasoning_effort = \"off\"");
        sb.AppendLine();
        sb.AppendLine("[features]");
        sb.AppendLine($"web_search = {(config.AgentWebSearch ? "true" : "false")}");

        WriteAtomic(ConfigPath, sb.ToString());
    }

    private static void WriteAtomic(string targetPath, string content)
    {
        lock (WriteGate)
        {
            var temp = targetPath + ".tmp";
            for (var attempt = 0; attempt < 6; attempt++)
            {
                try
                {
                    if (File.Exists(temp))
                        File.Delete(temp);

                    File.WriteAllText(temp, content, Encoding.UTF8);

                    if (File.Exists(targetPath))
                        File.Replace(temp, targetPath, null, ignoreMetadataErrors: true);
                    else
                        File.Move(temp, targetPath);

                    return;
                }
                catch (IOException) when (attempt < 5)
                {
                    Thread.Sleep(30 * (attempt + 1));
                }
            }

            File.WriteAllText(targetPath, content, Encoding.UTF8);
        }
    }

    private static string MapApprovalMode(string? mode) => mode?.ToLowerInvariant() switch
    {
        "never" => "auto",
        "always" => "suggest",
        "readonly" => "suggest",
        _ => "suggest",
    };

    private static void WriteMcpJson(AppConfig config)
    {
        var servers = new Dictionary<string, object>();
        foreach (var s in config.McpServers.Where(x => x.Enabled))
        {
            var id = string.IsNullOrWhiteSpace(s.Id) ? Guid.NewGuid().ToString("N")[..8] : s.Id;
            if (s.IsRemote && !string.IsNullOrWhiteSpace(s.Url))
            {
                servers[id] = new Dictionary<string, object?>
                {
                    ["url"] = s.Url,
                    ["transport"] = "http"
                };
            }
            else
            {
                servers[id] = new Dictionary<string, object?>
                {
                    ["command"] = s.Command,
                    ["args"] = s.Arguments.ToArray(),
                };
                if (!string.IsNullOrWhiteSpace(s.WorkingDirectory))
                    ((Dictionary<string, object?>)servers[id])["cwd"] = s.WorkingDirectory;
            }
        }

        var root = new Dictionary<string, object> { ["mcpServers"] = servers };
        var json = JsonSerializer.Serialize(root, new JsonSerializerOptions { WriteIndented = true });
        WriteAtomic(McpPath, json);
    }

    private static string EscapeToml(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static void EnsureDefaultPlaybooks()
    {
        var dir = Path.Combine(HomeDirectory, "playbooks");
        Directory.CreateDirectory(dir);

        WriteIfMissing(Path.Combine(dir, "blueprint-repo.yaml"), """
            id: blueprint-repo
            name: 仓库 Blueprint 调研
            description: 只读探索代码库并输出结构化 Blueprint（Plan 模式推荐）
            strategy: blueprint
            system_append: |
              优先列出顶层目录与关键入口文件；引用路径时使用相对工作区路径。
            steps:
              - 浏览仓库结构与 README / 构建脚本
              - 定位与用户任务相关的模块
              - 输出 Blueprint（目标 / 步骤 / 风险 / 验收标准）
            """);

        WriteIfMissing(Path.Combine(dir, "execute-with-verify.yaml"), """
            id: execute-with-verify
            name: Execute + Verify
            description: 执行改动后自动运行 dotnet test 验收
            strategy: execute
            steps:
              - 理解任务并最小化改动
              - 完成实现并自检
              - 等待 Harness Verify 阶段总结测试结果
            verify:
              steps:
                - command: dotnet build --no-restore -v minimal
                  name: build
                  optional: true
                  timeout_seconds: 120
                - command: dotnet test --no-build --verbosity minimal
                  name: test
                  optional: true
                  timeout_seconds: 180
            """);
    }

    private static void WriteBuiltinToolSchema()
    {
        var dir = Path.Combine(HomeDirectory, "tools");
        Directory.CreateDirectory(dir);
        WriteIfMissing(
            Path.Combine(dir, "builtin-openai-tools.json"),
            HarnessMarketToolSchema.BuildOpenAiBuiltinToolsJson());
    }

    private static void WriteIfMissing(string path, string content)
    {
        if (File.Exists(path)) return;
        try
        {
            File.WriteAllText(path, content.Replace("\r\n", "\n"), Encoding.UTF8);
        }
        catch (IOException)
        {
            // 并发写入或文件占用时不阻断 Apply
        }
    }

    private static void EnsureDefaultMemory()
    {
        var memoryRoot = Path.Combine(HomeDirectory, "memory");
        Directory.CreateDirectory(memoryRoot);
        Directory.CreateDirectory(Path.Combine(memoryRoot, "domains", "general"));
        Directory.CreateDirectory(Path.Combine(memoryRoot, "domains", "coding"));
        Directory.CreateDirectory(Path.Combine(HomeDirectory, "session"));

        WriteIfMissing(Path.Combine(HomeDirectory, "core.yaml"), """
            # DSD Harness L0 驾驭层（DeepSeek Desktop 原创，可参考 Harness 4.0 思想自行编辑）
            constraints:
              must_confirm:
                - 写文件、run_shell（Execute 阶段由 ApprovalGate 强制执行）
              never_do:
                - 编造未在 Observation 中出现的路径或 API
                - Blueprint 阶段调用工具
            pitfalls:
              - 网页 Model 可能截断 tool_call，Harness 会忽略 Blueprint 阶段的工具调用
              - 工作区外路径会被 WorkspacePathGuard 拒绝
            """);

        WriteIfMissing(Path.Combine(memoryRoot, "L2_behavior.yaml"), """
            # L2 行为层：你的偏好（可直接编辑）
            preferences:
              - 先 Explore 再 Execute，避免未调研就改代码
              - Blueprint 模式用于 Plan/方案，Execute 用于落地
            """);

        WriteIfMissing(Path.Combine(memoryRoot, "domains", "registry.json"), """
            {
              "domains": [
                { "id": "coding", "name": "编程开发", "keywords": ["代码", "bug", "dotnet", "csharp", "测试"] },
                { "id": "harness", "name": "Agent 系统", "keywords": ["harness", "agent", "playbook", "mcp"] },
                { "id": "work", "name": "工作文档", "keywords": ["报告", "邮件", "文档"] }
              ]
            }
            """);

        WriteIfMissing(Path.Combine(memoryRoot, "domains", "general", "L1_context.yaml"), """
            current_context:
              scenario: 通用任务
              note: 可在 ~/.deepseek/memory/domains/<domain>/ 下维护 L1/L3
            """);

        WriteIfMissing(Path.Combine(memoryRoot, "domains", "coding", "L3_cognitive.yaml"), """
            principles:
              - 最小 diff，匹配现有代码风格
              - 改完后优先 dotnet test / 项目既有验证脚本
            """);
    }
}
