using System.IO;
using System.Text;
using System.Text.Json;
using DeepSeekBrowser.Models;

namespace DeepSeekBrowser.Services.DeepSeekTui;

/// <summary>
/// 将桌面端设置同步到官方配置目录 <c>~/.deepseek/</c>（见 deepseek-tui.com/zh/docs）。
/// </summary>
public static class DeepSeekTuiConfigSync
{
    private static readonly object WriteGate = new();

    public static string HomeDirectory =>
        Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".deepseek");

    public static string ConfigPath => Path.Combine(HomeDirectory, "config.toml");

    public static string McpPath => Path.Combine(HomeDirectory, "mcp.json");

    public static void Apply(AppConfig config)
    {
        Directory.CreateDirectory(HomeDirectory);
        Directory.CreateDirectory(Path.Combine(HomeDirectory, "skills"));

        WriteConfigToml(config);
        WriteMcpJson(config);
    }

    private static void WriteConfigToml(AppConfig config)
    {
        var snap = Chat2ApiProviderService.Build(config);
        var apiKey = snap.ApiKeyForClients;
        var tuiBaseUrl = InternalChatChannel.ResolveTuiLlmBaseUrl(config);

        var defaultMode = string.Equals(config.DefaultAgentStrategy, AgentStrategies.Plan, StringComparison.OrdinalIgnoreCase)
            ? "plan"
            : "agent";

        var approval = MapApprovalMode(config.AgentApprovalMode);

        var sb = new StringBuilder();
        sb.AppendLine("# Generated by DeepSeek Desktop");
        sb.AppendLine("# LLM：桌面模块进程内直连网页会话（internal://desktop）；不经 5111 等本地代理端口");
        if (tuiBaseUrl is null)
            sb.AppendLine("# base_url 未设置：仅网页登录时 TUI 子进程 LLM 待进程内 IPC；可填写 DeepSeek 官方 API Key 作为替代");
        sb.AppendLine();
        sb.AppendLine($"api_key = \"{EscapeToml(apiKey)}\"");
        if (!string.IsNullOrWhiteSpace(tuiBaseUrl))
            sb.AppendLine($"base_url = \"{EscapeToml(tuiBaseUrl)}\"");
        sb.AppendLine("default_text_model = \"deepseek-v4-pro\"");
        sb.AppendLine();
        sb.AppendLine("[runtime_api]");
        sb.AppendLine("cors_origins = [\"https://ds-agent.local\"]");
        sb.AppendLine();
        sb.AppendLine("[ui]");
        sb.AppendLine($"default_mode = \"{defaultMode}\"");
        sb.AppendLine($"approval_mode = \"{approval}\"");

        var reasoningEffort = config.AgentDeepThinking ? "high" : "off";
        sb.AppendLine($"reasoning_effort = \"{reasoningEffort}\"");

        sb.AppendLine();
        sb.AppendLine("[features]");
        sb.AppendLine($"web_search = {(config.AgentWebSearch ? "true" : "false")}");

        WriteAtomic(ConfigPath, sb.ToString());
    }

    private static void WriteAtomic(string targetPath, string content)
    {
        lock (WriteGate)
        {
            var temp = targetPath + ".tmp";
            for (var attempt = 0; attempt < 6; attempt++)
            {
                try
                {
                    if (File.Exists(temp))
                        File.Delete(temp);

                    File.WriteAllText(temp, content, Encoding.UTF8);

                    if (File.Exists(targetPath))
                        File.Replace(temp, targetPath, null, ignoreMetadataErrors: true);
                    else
                        File.Move(temp, targetPath);

                    return;
                }
                catch (IOException) when (attempt < 5)
                {
                    Thread.Sleep(30 * (attempt + 1));
                }
            }

            File.WriteAllText(targetPath, content, Encoding.UTF8);
        }
    }

    private static string MapApprovalMode(string? mode) => mode?.ToLowerInvariant() switch
    {
        "never" => "auto",
        "always" => "suggest",
        "readonly" => "suggest",
        _ => "suggest",
    };

    private static void WriteMcpJson(AppConfig config)
    {
        var servers = new Dictionary<string, object>();
        foreach (var s in config.McpServers.Where(x => x.Enabled))
        {
            var id = string.IsNullOrWhiteSpace(s.Id) ? Guid.NewGuid().ToString("N")[..8] : s.Id;
            if (s.IsRemote && !string.IsNullOrWhiteSpace(s.Url))
            {
                servers[id] = new Dictionary<string, object?>
                {
                    ["url"] = s.Url,
                    ["transport"] = "http"
                };
            }
            else
            {
                servers[id] = new Dictionary<string, object?>
                {
                    ["command"] = s.Command,
                    ["args"] = s.Arguments.ToArray(),
                };
                if (!string.IsNullOrWhiteSpace(s.WorkingDirectory))
                    ((Dictionary<string, object?>)servers[id])["cwd"] = s.WorkingDirectory;
            }
        }

        var root = new Dictionary<string, object> { ["mcpServers"] = servers };
        var json = JsonSerializer.Serialize(root, new JsonSerializerOptions { WriteIndented = true });
        WriteAtomic(McpPath, json);
    }

    private static string EscapeToml(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
